export const studyField = [
  "Agriculture",
  "Science",
  "Mathematics",
  "History",
  "Literature",
  "Computer Science",
  "Physics",
  "Chemistry",
  "Biology",
  "Economics",
  "Philosophy",
  "Engineering",
  "Psychology",
  "Sociology",
  "Political Science",
  "Business",
  "Arts",
  "Law",
  "Medicine",
  "Environmental Studies",
  "Anthropology",
  "Linguistics",
  "Education",
  "Geography",
];

export const projectType = [
  "Narrative Essay",
  "Descriptive Essay",
  "Argumentative Essay",
  "Analytical Essay",
  "Reflective Essay",
  "Dissertations/Theses",
  "Research Dissertation",
  "Literature-Based Dissertation",
  "Research Report",
  "Case Study Report",
  "Business Report",
  "Annotated Bibliographies",
  "Literature Reviews",
  "Critical Reviews",
  "Research Proposals",
  "Policy Papers",
  "Comparative Studies",
  "Book Reviews",
];

export const languages = ["English (US)", "English (UK)"];

export const writingStyles = [
  "Formal",
  "Informal",
  "Casual",
  "Technical",
  "Persuasive",
  "Narrative",
  "Expository",
  "Journalistic",
  "Creative",
  "Academic",
  "Business",
  "Script",
];

export const citationStyles = [
  "American Psychological Association",
  "Modern Language Association",
  "Chicago Manual of Style",
  "Harvard Referencing Style",
  "Vancouver Referencing Style",
];

export const aiLevels = ["Low", "Medium", "High"];

export const accessType = [
  { value: "View", label: "View access" },
  { value: "Edit", label: "Edit access" },
];

export const pricingData = [
  {
    name: "Free",
    duration: 0,
    renew: "Life",
    amount: 0,
    description: "Enjoy basic features at no cost.",
    features: [
      "Access to limited features",
      "Community support",
      "Basic analytics",
      "Limited storage",
      "Ad-supported experience",
    ],
    isPopular: false,
  },
  {
    name: "Basic",
    amount: 30000,
    duration: 30,
    renew: "Monthly",
    description: "Billed monthly",
    features: [
      "Full access to standard features",
      "Email support",
      "Advanced analytics",
      "Increased storage",
      "No ads",
    ],
    isPopular: true,
  },
  {
    name: "Plus",
    amount: 100000,
    description: "Billed annually",
    duration: 365,
    renew: "Anually",
    features: [
      "Full access to all features",
      "Priority support",
      "Premium analytics",
      "Unlimited storage",
      "Collaborative tools",
    ],
    isPopular: false,
  },
];

export const translate = [
  "Afrikaans",
  "Albanian",
  "Amharic",
  "Arabic",
  "Armenian",
  "Azerbaijani",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bosnian",
  "Bulgarian",
  "Catalan",
  "Cebuano",
  "Chichewa",
  "Chinese (Simplified)",
  "Chinese (Traditional)",
  "Corsican",
  "Croatian",
  "Czech",
  "Danish",
  "Dutch",
  "English",
  "Esperanto",
  "Estonian",
  "Filipino",
  "Finnish",
  "French",
  "Frisian",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Gujarati",
  "Haitian Creole",
  "Hausa",
  "Hawaiian",
  "Hebrew",
  "Hindi",
  "Hmong",
  "Hungarian",
  "Icelandic",
  "Igbo",
  "Indonesian",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kazakh",
  "Khmer",
  "Kinyarwanda",
  "Korean",
  "Kurdish (Kurmanji)",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Lithuanian",
  "Luxembourgish",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Maori",
  "Marathi",
  "Mongolian",
  "Myanmar (Burmese)",
  "Nepali",
  "Norwegian",
  "Odia (Oriya)",
  "Pashto",
  "Persian",
  "Polish",
  "Portuguese",
  "Punjabi",
  "Romanian",
  "Russian",
  "Samoan",
  "Scots Gaelic",
  "Serbian",
  "Sesotho",
  "Shona",
  "Sindhi",
  "Sinhala",
  "Slovak",
  "Slovenian",
  "Somali",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swedish",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Turkish",
  "Turkmen",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Vietnamese",
  "Welsh",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zulu",
];
